### ISSUE TITLE
[CDL-003] Implementing Data Encryption

### ISSUE THREAD

**Issue by zyan225** [zyan225/Collaborative_content_coding#146]
Implementing the data encryption method.
Check that data is encrypted.

**Comment by ywu666** [comment]
The Research about the database encryption: https://docs.google.com/document/u/1/d/1Rl16V1JwC5RHeLZJQAvOhZSOkTGoBrYhJYAD_r1EKRA/edit?usp=drive_web&ouid=117407212200091060129

**Comment by ywu666** [comment]
The flow diagram of encryption and decryption: https://app.diagrams.net/#G1WJuds2u_HFYsUBS-pbk7BCmxS5MYXMZU
